export const ADD_ITEM = 'ADD_ITEM';
export const FETCH_DATA = 'FETCH_DATA';
export const FILTER_BY_BRAND = 'FILTER_BY_BRAND';
export const UPDATE_BRAND_FILTER = 'UPDATE_BRAND_FILTER';
export const UPDATE_CATEGORY_FILTER = 'UPDATE_CATEGORY_FILTER';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
